# Generated by Django 5.1.7 on 2025-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
